server:
  port: 8762
spring:
  application:
    name: Eureka-Server
eureka:
  instance:
    hostname: 192.168.107.241
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.107.242:8763/eureka/,http://192.168.107.145:8761/eureka/
    server:
      enable-self-preservation: false