
server:
  port: 8085
eureka:
  instance:
    hostname: slave2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://master:8088/eureka/,http://slave1:8086/eureka/