
server:
  port: 8061
eureka:
  instance:
    hostname: master
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      #defaultZone: http://slave1:8086/eureka/,http://slave2:8085/eureka/
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/