server:
  port: 8763
spring:
  application:
    name: Eureka-Server
eureka:
  instance:
    #hostname: 192.168.107.242
    hostname: eureka-server-three
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #defaultZone: http://192.168.107.241:8762/eureka/,http://192.168.107.145:8761/eureka/
      defaultZone: http://eureka-server-two:8762/eureka/,http://eureka-server-one:8761/eureka/
    #server:
      #enable-self-preservation: false
