
server:
  port: 8662
spring:
  application:
    name: service-client
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-one:8761/eureka/
      #defaultZone: http://eureka-server-one:8761/eureka/,http://eureka-server-two:8762/eureka/,http://eureka-server-three:8763/eureka/