
server:
  port: 8089
spring:
  application:
    name: service-web
    
eureka:
  client:
    serviceUrl:
     #defaultZone: http://master:8088/eureka/,http://slave1:8086/eureka/,http://slave2:8085/eureka/
     defaultZone: http://master:8088/eureka/