eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-one:8761/eureka/
      #defaultZone: http://eureka-server-one:8761/eureka/,http://eureka-server-two:8762/eureka/,http://eureka-server-three:8763/eureka/
server:
  port: 8462
spring:
  application:
    name: service-gateway
  sleuth:
    sampler:
      probability: 1
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
      - AddResponseHeader=X-Response-Default-Foo, Default-Bar
      - name: RequestRateLimiter
        args:
          redis-rate-limiter.replenishRate: 1  #令牌桶的容积
          redis-rate-limiter.burstCapacity: 1  #流速 每秒
          rate-limiter: "#{@defaultRedisRateLimiter}"  #SPEL表达式去的对应的bean
          key-resolver: "#{@remoteAddressKeyResolver}" #SPEL表达式去的对应的bean
      routes:
      # =====================================
      - id: authorization-server
        uri: lb://authorization-server
        predicates:
        - Path=/authorization-server/**
        filters:
        - StripPrefix=1
        - AddResponseHeader=foo, bar
      - id: producer
        uri: lb://producer
        predicates:
        - Path=/producer/**
        filters:
        - StripPrefix=1
        - AddResponseHeader=foo, bar  
    


