server:
  port: 8761
spring:
  application:
    name: Eureka-Server
eureka:
  instance:
    #hostname: 192.168.107.145
    hostname: eureka-server-one
  client:
    #registerWithEureka: true
    registerWithEureka: false
    #fetchRegistry: true
    fetchRegistry: false
    service-url:
      defaultZone: http://eureka-server-one:8761/eureka/
      #defaultZone: http://eureka-server-two:8762/eureka/,http://eureka-server-three:8763/eureka/
