eureka:
  client:
    serviceUrl:
      #defaultZone: http://master:8088/eureka/,http://slave1:8086/eureka/,http://slave2:8085/eureka/
      defaultZone: http://eureka-server-one:8761/eureka/,http://eureka-server-two:8762/eureka/,http://eureka-server-three:8763/eureka/
server:
  port: 8561
spring:
  application:
    name: service-ribbon